name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  detekt-job:
    name: Run Detekt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Detekt all
        uses: natiginfo/action-detekt-all@1.15.0
        with:
          args: --parallel --config ./config/detekt/detekt.yml
