name: Instrumented-Tests

on:
  push:
    branches: [ feature/#NO_ISSUE-CI-instrumented-tests ]
  pull_request:
    branches: [ feature/#NO_ISSUE-CI-instrumented-tests ]

jobs:
  test:
    runs-on: macOS-latest
    strategy:
      matrix:
        api-level: [ 23, 30]
        arch: [x86]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          script: ./gradlew connectedCheck
