name: Instrumented-Tests

on:
  push:
    branches: [ feature/#NO_ISSUE-CI-instrumented-tests ]
  pull_request:
    branches: [ feature/#NO_ISSUE-CI-instrumented-tests ]

jobs:
  test-job:
    name: Run Tests
    runs-on: macos-latest

    strategy:
      matrix:
        api-level: [23, 29]

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit tests
        run: bash ./gradlew test --stacktrace

      - name: Instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{matrix.api-level}}
          script: ./gradlew connectedCheck --stacktrace



